[package]
name = "dig"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dig"
path = "src/main.rs"

[lib]
name = "dig_lib"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["net", "io-util", "time", "rt-multi-thread", "macros"] }
thiserror = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2"] }
